var hierarchy =
[
    [ "com.company.projectoop.model.Cci", "classcom_1_1company_1_1projectoop_1_1model_1_1_cci.html", null ],
    [ "com.company.projectoop.model.Denominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_denominator.html", null ],
    [ "com.company.projectoop.model.Finance_coverage", "classcom_1_1company_1_1projectoop_1_1model_1_1_finance__coverage.html", null ],
    [ "com.company.projectoop.model.Focus_area_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_focus__area__code.html", null ],
    [ "com.company.projectoop.model.Forecast_denominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_forecast__denominator.html", null ],
    [ "com.company.projectoop.model.Forecast_nominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_forecast__nominator.html", null ],
    [ "com.company.projectoop.model.Forecast_value", "classcom_1_1company_1_1projectoop_1_1model_1_1_forecast__value.html", null ],
    [ "com.company.projectoop.model.Fund", "classcom_1_1company_1_1projectoop_1_1model_1_1_fund.html", null ],
    [ "com.company.projectoop.model.Implemented_denominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_implemented__denominator.html", null ],
    [ "com.company.projectoop.model.Implemented_nominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_implemented__nominator.html", null ],
    [ "com.company.projectoop.model.Implemented_value", "classcom_1_1company_1_1projectoop_1_1model_1_1_implemented__value.html", null ],
    [ "com.company.projectoop.model.Ind_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_ind__code.html", null ],
    [ "com.company.projectoop.model.Ind_group_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_ind__group__code.html", null ],
    [ "com.company.projectoop.model.Ind_group_name", "classcom_1_1company_1_1projectoop_1_1model_1_1_ind__group__name.html", null ],
    [ "com.company.projectoop.model.Indicator_long_name", "classcom_1_1company_1_1projectoop_1_1model_1_1_indicator__long__name.html", null ],
    [ "com.company.projectoop.model.Indicator_short_name", "classcom_1_1company_1_1projectoop_1_1model_1_1_indicator__short__name.html", null ],
    [ "com.company.projectoop.model.Indicator_type_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_indicator__type__code.html", null ],
    [ "com.company.projectoop.model.Investment_priority", "classcom_1_1company_1_1projectoop_1_1model_1_1_investment__priority.html", null ],
    [ "com.company.projectoop.model.Ir_ver", "classcom_1_1company_1_1projectoop_1_1model_1_1_ir__ver.html", null ],
    [ "com.company.projectoop.model.Is_division", "classcom_1_1company_1_1projectoop_1_1model_1_1_is__division.html", null ],
    [ "com.company.projectoop.controller.MainController", "classcom_1_1company_1_1projectoop_1_1controller_1_1_main_controller.html", null ],
    [ "com.company.projectoop.model.Measure_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_measure__code.html", null ],
    [ "com.company.projectoop.model.Measurement_unit", "classcom_1_1company_1_1projectoop_1_1model_1_1_measurement__unit.html", null ],
    [ "com.company.projectoop.model.Ms", "classcom_1_1company_1_1projectoop_1_1model_1_1_ms.html", null ],
    [ "com.company.projectoop.model.Ms_name", "classcom_1_1company_1_1projectoop_1_1model_1_1_ms__name.html", null ],
    [ "com.company.projectoop.model.Ms_op_coverage", "classcom_1_1company_1_1projectoop_1_1model_1_1_ms__op__coverage.html", null ],
    [ "com.company.projectoop.model.Nominator", "classcom_1_1company_1_1projectoop_1_1model_1_1_nominator.html", null ],
    [ "com.company.projectoop.parsing.Parsecsv", "interfacecom_1_1company_1_1projectoop_1_1parsing_1_1_parsecsv.html", [
      [ "com.company.projectoop.parsing.Parsecsv_Impl", "classcom_1_1company_1_1projectoop_1_1parsing_1_1_parsecsv___impl.html", null ]
    ] ],
    [ "com.company.projectoop.parsing.Parsejson", "interfacecom_1_1company_1_1projectoop_1_1parsing_1_1_parsejson.html", [
      [ "com.company.projectoop.parsing.Parsejson_Impl", "classcom_1_1company_1_1projectoop_1_1parsing_1_1_parsejson___impl.html", null ]
    ] ],
    [ "com.company.projectoop.model.Priority_code", "classcom_1_1company_1_1projectoop_1_1model_1_1_priority__code.html", null ],
    [ "com.company.projectoop.ProjectoopApplication", "classcom_1_1company_1_1projectoop_1_1_projectoop_application.html", null ],
    [ "com.company.projectoop.table.Riga_metadata", "classcom_1_1company_1_1projectoop_1_1table_1_1_riga__metadata.html", null ],
    [ "com.company.projectoop.table.Riga_tabella", "classcom_1_1company_1_1projectoop_1_1table_1_1_riga__tabella.html", null ],
    [ "com.company.projectoop.model.Target_value", "classcom_1_1company_1_1projectoop_1_1model_1_1_target__value.html", null ],
    [ "com.company.projectoop.model.Title", "classcom_1_1company_1_1projectoop_1_1model_1_1_title.html", null ],
    [ "com.company.projectoop.model.To", "classcom_1_1company_1_1projectoop_1_1model_1_1_to.html", null ],
    [ "com.company.projectoop.model.To_short", "classcom_1_1company_1_1projectoop_1_1model_1_1_to__short.html", null ],
    [ "com.company.projectoop.model.Ver", "classcom_1_1company_1_1projectoop_1_1model_1_1_ver.html", null ],
    [ "com.company.projectoop.model.Visualize_by_ms", "classcom_1_1company_1_1projectoop_1_1model_1_1_visualize__by__ms.html", null ],
    [ "com.company.projectoop.model.Visualize_by_to", "classcom_1_1company_1_1projectoop_1_1model_1_1_visualize__by__to.html", null ],
    [ "com.company.projectoop.model.Year", "classcom_1_1company_1_1projectoop_1_1model_1_1_year.html", null ]
];